// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDM6N0j6yTOc4GO0idlMVOflSVjij67g',
    appId: '1:317884244646:web:e10e1b714093121e96ca67',
    messagingSenderId: '317884244646',
    projectId: 'su-learning-companion',
    authDomain: 'su-learning-companion.firebaseapp.com',
    storageBucket: 'su-learning-companion.firebasestorage.app',
    measurementId: 'G-4PG1RK4SYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0MQMa0lLoZ7FTK5YnzXhRey6bfnD--qc',
    appId: '1:317884244646:android:a2cf0bde4c0467e396ca67',
    messagingSenderId: '317884244646',
    projectId: 'su-learning-companion',
    storageBucket: 'su-learning-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztLlsAuBfVcBADQ_tDCXW9CvPq_efgk8',
    appId: '1:317884244646:ios:2cfa81a3af662ac996ca67',
    messagingSenderId: '317884244646',
    projectId: 'su-learning-companion',
    storageBucket: 'su-learning-companion.firebasestorage.app',
    iosBundleId: 'com.example.suLearningCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztLlsAuBfVcBADQ_tDCXW9CvPq_efgk8',
    appId: '1:317884244646:ios:2cfa81a3af662ac996ca67',
    messagingSenderId: '317884244646',
    projectId: 'su-learning-companion',
    storageBucket: 'su-learning-companion.firebasestorage.app',
    iosBundleId: 'com.example.suLearningCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwDM6N0j6yTOc4GO0idlMVOflSVjij67g',
    appId: '1:317884244646:web:65c04c63681cd54e96ca67',
    messagingSenderId: '317884244646',
    projectId: 'su-learning-companion',
    authDomain: 'su-learning-companion.firebaseapp.com',
    storageBucket: 'su-learning-companion.firebasestorage.app',
    measurementId: 'G-5KJ29FW2M8',
  );
}
